################################################################
#
# Configuration sample for Traefik v2.
# Read more: https://raw.githubusercontent.com/containous/traefik/master/traefik.sample.toml
#
################################################################

################################################################
# Global configuration
################################################################
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecured]
    address = ":443"

[certificatesResolvers.mydnschallenge.acme]
  email    = "${EMAIL}"
  storage  = "/letsencrypt/acme.json"
  [certificatesResolvers.mydnschallenge.acme.dnsChallenge]
    provider = "${PROVIDER}"
    delayBeforeCheck = 0

################################################################
# Traefik logs configuration
################################################################

# Enabled by default and log to stdout
[log]
  level = "DEBUG"

################################################################
# Access logs configuration
################################################################

# Enable access logs
[accessLog]

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]
  dashboard = true

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[providers.docker]
  swarmMode = true
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"

################################################################
# Traefik Pilot configuration backend
################################################################
[pilot]
    token = "${PILOT_TOKEN}"

[experimental.plugins.cache]
  modulename = "github.com/traefik/plugin-simplecache"
  version = "v0.2.1"
