version: "3.7"

networks:
  public_network:
    driver: overlay
    external: true

  db_network:
    driver: overlay
    external: true

services:
  wordpress:
    image: tanngoc93/wordpress:5.4-php7.4-apache
    volumes:
      - "/volumes/com.thedogpaws/localhost/html:/var/www/html"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
    networks:
      - db_network
      - public_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public_network"
        # 
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        #
        - "traefik.http.routers.wordpress.rule=Host(`thedogpaws.com`, `www.thedogpaws.com`)"
        - "traefik.http.routers.wordpress.entrypoints=web"
        - "traefik.http.routers.wordpress.middlewares=redirect-to-https"
        # 
        - "traefik.http.services.wordpress-svc.loadbalancer.server.port=80"
        # 
        - "traefik.http.routers.wordpress-secured.rule=Host(`thedogpaws.com`)"
        - "traefik.http.routers.wordpress-secured.entrypoints=websecured"
        - "traefik.http.routers.wordpress-secured.tls=true"
        - "traefik.http.routers.wordpress-secured.tls.certresolver=mytlschallenge"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
