version: "3.8"

networks:
  public_network:
    driver: overlay
    external: true

services:
  frontend:
    image: tanngoc93/com.thedogpaws:latest
    command: bash -c "passenger start"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      PREFIX: "${PREFIX}"
      SITE_NAME: "${SITE_NAME}"
      SITE_LOGO: "${SITE_LOGO}"
      SITE_FAVICON: "${SITE_FAVICON}"
      SITE_FEATURE_IMAGE: "${SITE_FEATURE_IMAGE}"
      COUPON_PAGE_DESCRIPTION: "${COUPON_PAGE_DESCRIPTION}"
      COUPON_PAGE_TITLE: "${COUPON_PAGE_TITLE}"
      COUPON_API: "${COUPON_API}"
      BLOG_API: "${BLOG_API}"
    networks:
      - public_network
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public_network"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.stripprefix-middleware.stripprefix.prefixes=/coupons"
        #
        - "traefik.http.routers.frontend-http.rule=Host(`${DOMAIN}`) && PathPrefix(`/coupons`)"
        - "traefik.http.routers.frontend-http.entrypoints=web"
        - "traefik.http.routers.frontend-http.middlewares=redirect-to-https@docker"
        - "traefik.http.routers.frontend-http.middlewares=stripprefix-middleware@docker"
        # 
        - "traefik.http.services.frontend-svc.loadbalancer.server.port=80"
        # 
        - "traefik.http.routers.frontend-https.rule=Host(`${DOMAIN}`) && PathPrefix(`/coupons`)"
        - "traefik.http.routers.frontend-https.entrypoints=websecured"
        - "traefik.http.routers.frontend-https.tls=true"
        - "traefik.http.routers.frontend-https.tls.certresolver=mytlschallenge"
        - "traefik.http.routers.frontend-https.middlewares=stripprefix-middleware@docker"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
