version: "3.8"

networks:
  public_network:
    driver: overlay
    external: true

services:
  traefik:
    image: traefik:v2.3.7
    volumes:
      - "/volumes/traefik/letsencrypt:/letsencrypt"
      - "/volumes/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public_network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      - "EMAIL=${EMAIL}"
      - "PILOT_TOKEN=${PILOT_TOKEN}"
      - "CF_API_EMAIL=${CF_API_EMAIL}"
      - "CF_API_KEY=${CF_API_KEY}"
      - "PROVIDER=${PROVIDER}"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public_network"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        #
        - "traefik.http.routers.proxy.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.proxy.entrypoints=web"
        - "traefik.http.routers.proxy.middlewares=redirect-to-https@docker"
        # 
        - "traefik.http.services.proxy-svc.loadbalancer.server.port=8080"
        # 
        - "traefik.http.routers.proxy-secured.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.proxy-secured.entrypoints=websecured"
        - "traefik.http.routers.proxy-secured.service=api@internal"
        - "traefik.http.routers.proxy-secured.tls=true"
        - "traefik.http.routers.proxy-secured.tls.certresolver=mydnschallenge"
        #
        - "traefik.http.routers.proxy-https.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=deployer:$$apr1$$aq9QxmNl$$oHp76FRNe4Z0WWR67oKHQ1"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  system-prune:
    image: docker
    command: docker system prune --all --force
    deploy:
      mode: global
      labels:
        - "traefik.enable=false"
      restart_policy:
        delay: 24h
