version: "3.7"

networks:
  public_network:
    driver: overlay
    external: true

services:
  varnish:
    image: varnish:6.0.6
    volumes:
      - "/volumes/varnish/conf/default.vcl:/etc/varnish/default.vcl:ro"
    environment:
      VARNISH_SIZE: 512M
    networks:
      - public_network
    depends_on:
      - wordpress
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public_network"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        #
        - "traefik.http.routers.varnish.rule=Host(`${DOMAIN}`, `www.${DOMAIN}`)"
        - "traefik.http.routers.varnish.entrypoints=web"
        - "traefik.http.routers.varnish.middlewares=redirect-to-https@docker"
        # 
        - "traefik.http.services.varnish-svc.loadbalancer.server.port=80"
        # 
        - "traefik.http.routers.varnish-secured.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.varnish-secured.entrypoints=websecured"
        - "traefik.http.routers.varnish-secured.tls=true"
        - "traefik.http.routers.varnish-secured.tls.certresolver=mydnschallenge"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
